languageCode = "en-us"
title = "JonTK"
baseurl = "https://www.jontk.com/"
googleAnalytics = ""
disqusShortname = "XYW"

[params]
  custom_css = ["css/foundation.min.css", "css/app.css"]
  custom_js = ["js/vendor/foundation.min.js", "js/app.js", "js/vendor/what-input.js"]
