languageCode = "en-us"
title = "JonTK"
baseurl = "https://www.jontk.com/"

[params]
  custom_css = ["css/foundation.css", "css/site.css", "css/app.css"]


[[menu.main]]
   name = "Home"
   weight = -120
   identifier = "home"
   url = "/"
[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"
[[menu.main]]
   name = "Blog"
   weight = -100
   identifier = "blog"
   url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = -90
  identifier = "projects"
  url = "/projects/"
